FROM docker.io/library/alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk add --no-cache autoconf automake make perl tar
COPY . /src
WORKDIR /src
RUN autoreconf -i && ./configure --disable-container --prefix=/opt/selftest \
 && make && make install
