from repo_infra.markers import Marker, marker_line, parse_markers


def test_parses_a_yaml_marker_on_the_second_line():
    text = "name: CI\n# repo-infra: ci v1\n\non:\n"
    assert parse_markers(text) == [Marker(asset="ci", version=1, line=2)]


def test_parses_a_javascript_marker():
    text = "// repo-infra: workflow-lib v3\nmodule.exports = {};\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib", version=3, line=1)]


def test_parses_indented_block_markers_in_an_assembled_file():
    text = (
        "name: CI\n"
        "# repo-infra: ci v1\n"
        "jobs:\n"
        "  # repo-infra: ci-rust v2\n"
        "  fmt:\n"
        "    runs-on: ubuntu-latest\n"
        "  # repo-infra: ci-lib v1\n"
        "  lib:\n"
    )
    assert parse_markers(text) == [
        Marker(asset="ci", version=1, line=2),
        Marker(asset="ci-rust", version=2, line=4),
        Marker(asset="ci-lib", version=1, line=7),
    ]


def test_trailing_prose_after_the_version_is_allowed():
    text = "# repo-infra: release-pr v3 - do not delete this line\n"
    assert parse_markers(text) == [Marker(asset="release-pr", version=3, line=1)]


def test_ordinary_comments_are_not_markers():
    text = "# this file is generated by repo-infra\n# repo-infra v1\n# repo-infra: ci\n"
    assert parse_markers(text) == []


def test_marker_line_round_trips():
    line = marker_line("ci-python", 4, indent="  ")
    assert line == "  # repo-infra: ci-python v4"
    assert parse_markers(line + "\n") == [Marker(asset="ci-python", version=4, line=1)]


def test_marker_line_can_use_a_javascript_comment():
    assert marker_line("workflow-lib", 1, comment="//") == "// repo-infra: workflow-lib v1"


def test_asset_id_rejects_uppercase_letters():
    text = "# repo-infra: Workflow-Lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_rejects_underscores():
    text = "# repo-infra: workflow_lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_accepts_hyphens_in_lowercase():
    text = "# repo-infra: workflow-lib-v2 v1\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib-v2", version=1, line=1)]
