import pytest

from repo_infra.markers import Marker, marker_line, parse_markers, pristine, stamp, strip_stamp


def test_parses_a_yaml_marker_on_the_second_line():
    text = "name: CI\n# repo-infra: ci v1\n\non:\n"
    assert parse_markers(text) == [Marker(asset="ci", version=1, line=2)]


def test_parses_a_javascript_marker():
    text = "// repo-infra: workflow-lib v3\nmodule.exports = {};\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib", version=3, line=1)]


def test_parses_indented_block_markers_in_an_assembled_file():
    text = (
        "name: CI\n"
        "# repo-infra: ci v1\n"
        "jobs:\n"
        "  # repo-infra: ci-rust v2\n"
        "  fmt:\n"
        "    runs-on: ubuntu-latest\n"
        "  # repo-infra: ci-lib v1\n"
        "  lib:\n"
    )
    assert parse_markers(text) == [
        Marker(asset="ci", version=1, line=2),
        Marker(asset="ci-rust", version=2, line=4),
        Marker(asset="ci-lib", version=1, line=7),
    ]


def test_trailing_prose_after_the_version_is_allowed():
    text = "# repo-infra: release-pr v3 - do not delete this line\n"
    assert parse_markers(text) == [Marker(asset="release-pr", version=3, line=1)]


def test_ordinary_comments_are_not_markers():
    text = "# this file is generated by repo-infra\n# repo-infra v1\n# repo-infra: ci\n"
    assert parse_markers(text) == []


def test_marker_line_round_trips():
    line = marker_line("ci-python", 4, indent="  ")
    assert line == "  # repo-infra: ci-python v4"
    assert parse_markers(line + "\n") == [Marker(asset="ci-python", version=4, line=1)]


def test_marker_line_can_use_a_javascript_comment():
    assert marker_line("workflow-lib", 1, comment="//") == "// repo-infra: workflow-lib v1"


def test_marker_line_rejects_a_non_integer_version():
    # A manifest entry written as 1.0 instead of 1 must fail loudly here rather
    # than render "v1.0" -- a marker parse_markers's `v(\d+)` pattern can never
    # match, which would make the marker silently unreadable.
    with pytest.raises(ValueError):
        marker_line("ci", 1.5)


def test_asset_id_rejects_uppercase_letters():
    text = "# repo-infra: Workflow-Lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_rejects_underscores():
    text = "# repo-infra: workflow_lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_accepts_hyphens_in_lowercase():
    text = "# repo-infra: workflow-lib-v2 v1\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib-v2", version=1, line=1)]


def test_dnl_is_a_marker_comment():
    # m4 assets comment with `dnl`, which discards the line instead of copying
    # it into the generated configure.
    found = parse_markers("dnl repo-infra: container-m4 v1\nAC_DEFUN([X], [])\n")
    assert [(m.asset, m.version, m.line) for m in found] == [("container-m4", 1, 1)]


def test_dnl_needs_a_word_boundary():
    # `dnlrepo-infra:` is not a comment in any language.
    assert parse_markers("dnlrepo-infra: container-m4 v1\n") == []


def test_marker_line_renders_the_dnl_comment():
    assert marker_line("container-m4", 1, comment="dnl") == "dnl repo-infra: container-m4 v1"


def test_a_double_dash_is_a_marker_comment():
    # Lua comments with `--`, and build/man-deflist.lua carries its marker that
    # way (D23). Without this the filter has no readable marker: check never
    # reports it, and apply refuses with "no rendered file carries that asset".
    found = parse_markers("-- repo-infra: man-lua v1\nfunction BulletList(el) end\n")
    assert [(m.asset, m.version, m.line) for m in found] == [("man-lua", 1, 1)]
    line = marker_line("man-lua", 1, comment="--")
    assert line == "-- repo-infra: man-lua v1"
    assert parse_markers(line + "\n") == [Marker(asset="man-lua", version=1, line=1)]


def test_a_lua_doc_comment_is_not_a_marker():
    # `---` opens a LuaDoc comment. The marker is exactly `--`.
    assert parse_markers("--- repo-infra: man-lua v1\n") == []


ASSEMBLED = ("name: CI\n# repo-infra: ci v2\njobs:\n"
             "  # repo-infra: ci-rust v3\n  rust:\n    runs-on: x\n")


def test_stamp_goes_on_the_first_marker_only():
    stamped = stamp(ASSEMBLED)
    lines = stamped.splitlines()
    assert lines[1].startswith("# repo-infra: ci v2 sha256=")
    assert len(lines[1].rsplit("=", 1)[1]) == 16
    assert lines[3] == "  # repo-infra: ci-rust v3"


def test_a_stamped_file_still_parses_to_the_same_markers():
    assert parse_markers(stamp(ASSEMBLED)) == parse_markers(ASSEMBLED)


def test_strip_stamp_undoes_stamp():
    assert strip_stamp(stamp(ASSEMBLED)) == ASSEMBLED


def test_stamping_twice_gives_the_same_text():
    assert stamp(stamp(ASSEMBLED)) == stamp(ASSEMBLED)


def test_pristine_is_true_for_untouched_stamped_text():
    assert pristine(stamp(ASSEMBLED)) is True


def test_pristine_is_false_after_an_edit_anywhere():
    edited = stamp(ASSEMBLED).replace("runs-on: x", "runs-on: y")
    assert pristine(edited) is False


def test_pristine_is_false_when_a_digit_of_the_stamp_changes():
    stamped = stamp(ASSEMBLED)
    digit = stamped.index("sha256=") + len("sha256=")
    flipped = "0" if stamped[digit] != "0" else "1"
    assert pristine(stamped[:digit] + flipped + stamped[digit + 1:]) is False


def test_pristine_is_none_without_a_stamp():
    assert pristine(ASSEMBLED) is None


def test_pristine_is_none_without_a_marker():
    assert pristine("no marker here\n") is None


def test_stamp_keeps_trailing_prose_on_the_marker_line():
    text = "# repo-infra: ci v2 do not delete this line\nx\n"
    stamped = stamp(text)
    assert stamped.splitlines()[0].startswith("# repo-infra: ci v2 do not delete this line sha256=")
    assert pristine(stamped) is True


def test_stamp_works_for_each_comment_style():
    for comment in ("#", "//", "--", "dnl"):
        text = f"{comment} repo-infra: x v1\nbody\n"
        assert pristine(stamp(text)) is True


def test_crlf_text_is_never_pristine_after_conversion():
    lf = stamp("# repo-infra: ci v2\njobs:\n")
    assert pristine(lf.replace("\n", "\r\n")) is not True
