from repo_infra.markers import Marker, parse_markers


def test_parses_a_yaml_marker_on_the_second_line():
    text = "name: CI\n# repo-infra: ci v1\n\non:\n"
    assert parse_markers(text) == [Marker(asset="ci", version=1, line=2)]


def test_parses_a_javascript_marker():
    text = "// repo-infra: workflow-lib v3\nmodule.exports = {};\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib", version=3, line=1)]


def test_trailing_prose_after_the_version_is_allowed():
    text = "# repo-infra: release-pr v3 - do not delete this line\n"
    assert parse_markers(text) == [Marker(asset="release-pr", version=3, line=1)]


def test_ordinary_comments_are_not_markers():
    text = "# this file is generated by repo-infra\n# repo-infra v1\n# repo-infra: ci\n"
    assert parse_markers(text) == []


def test_asset_id_rejects_uppercase_letters():
    text = "# repo-infra: Workflow-Lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_rejects_underscores():
    text = "# repo-infra: workflow_lib v1\n"
    assert parse_markers(text) == []


def test_asset_id_accepts_hyphens_in_lowercase():
    text = "# repo-infra: workflow-lib-v2 v1\n"
    assert parse_markers(text) == [Marker(asset="workflow-lib-v2", version=1, line=1)]


def test_dnl_is_a_marker_comment():
    # m4 assets comment with `dnl`, which discards the line instead of copying
    # it into the generated configure.
    found = parse_markers("dnl repo-infra: container-m4 v1\nAC_DEFUN([X], [])\n")
    assert [(m.asset, m.version, m.line) for m in found] == [("container-m4", 1, 1)]


def test_dnl_needs_a_word_boundary():
    # `dnlrepo-infra:` is not a comment in any language.
    assert parse_markers("dnlrepo-infra: container-m4 v1\n") == []


def test_a_double_dash_is_a_marker_comment():
    # Lua comments with `--`, and build/man-deflist.lua carries its marker that
    # way (D23). Without this the filter has no readable marker: check never
    # reports it, and apply refuses with "no rendered file carries that asset".
    found = parse_markers("-- repo-infra: man-lua v1\nfunction BulletList(el) end\n")
    assert [(m.asset, m.version, m.line) for m in found] == [("man-lua", 1, 1)]


def test_a_lua_doc_comment_is_not_a_marker():
    # `---` opens a LuaDoc comment. The marker is exactly `--`.
    assert parse_markers("--- repo-infra: man-lua v1\n") == []


def test_a_marker_followed_by_a_d29_stamp_still_parses():
    # v0.3.x appended ` sha256=<16 hex>` to the first marker line; files in the
    # field still carry it, and check reads them as the version they name.
    text = "# repo-infra: ci v2 sha256=0123456789abcdef\nx\n"
    assert parse_markers(text) == [Marker(asset="ci", version=2, line=1)]
