"""Write references/catalogue.md from the pieces themselves (D30).

`make catalogue` runs this. tests/test_catalogue.py fails when the committed
file differs, so the catalogue cannot fall behind the pieces it describes.
"""

import pathlib
import sys

from . import callers, workflow
from .pieces import load_pieces

GROUPS = (("ci", "CI: called from ci.yml"),
          ("release-build", "Release build: called from release-build.yml"),
          ("publish", "Publish: called from release-publish.yml"),
          ("release", "Release flow: installed, never called by hand"),
          ("build", "Build files"))
LABELS = (("Purpose", "Purpose"), ("Choose", "Choose it when"),
          ("Supplies", "The repository supplies"), ("Pieces", "Needs the pieces"),
          ("Produces", "Produces"))
INTRO = """# Catalogue

Generated by `make catalogue` from the header block, the inputs and the
secrets of every piece. Do not edit it by hand.

`apply --item <piece>` installs a piece 1:1 and commits it. A workflow piece
then needs a job in a caller; the snippet under each one is that job.
"""


def _cell(text):
    return " ".join(str(text).split()).replace("|", "\\|")


def _default(value):
    if value is None:
        return ""
    return f"`{_cell(value)}`" if value != "" else "`''`"


def entry(piece):
    lines = [f"### {piece.name} v{piece.version}", "", f"Installed at `{piece.target}`.", ""]
    for field, label in LABELS:
        if field in piece.header:
            lines += [f"**{label}:** {' '.join(piece.header[field].split())}", ""]
    if not piece.workflow:
        return "\n".join(lines)
    doc = workflow.load(piece.files[piece.target])
    face = workflow.interface(doc) or workflow.Interface({}, {}, ())
    if face.inputs:
        lines += ["| Input | Type | Required | Default | Description |",
                  "|---|---|---|---|---|"]
        lines += [f"| `{name}` | {_cell(spec['type'])} | {'yes' if spec['required'] else 'no'} | "
                  f"{_default(spec['default'])} | {_cell(spec['description'])} |"
                  for name, spec in face.inputs.items()]
        lines.append("")
    if face.secrets:
        lines += ["| Secret | Required | Description |", "|---|---|---|"]
        lines += [f"| `{name}` | {'yes' if spec['required'] else 'no'} | "
                  f"{_cell(spec['description'])} |" for name, spec in face.secrets.items()]
        lines.append("")
    if face.outputs:
        lines += ["**Outputs:** " + ", ".join(f"`{name}`" for name in face.outputs), ""]
    file = pathlib.PurePosixPath(piece.target).name
    lines += [f"**Permissions it needs:** "
              f"{callers.permission_text(callers.needed(file, {file: doc})) or 'none'}", ""]
    if "Call" in piece.header:
        lines += ["```yaml", piece.header["Call"], "```", ""]
    return "\n".join(lines)


def render(pieces):
    known = {group for group, _ in GROUPS}
    for piece in sorted(pieces.values(), key=lambda p: p.name):
        if piece.group not in known:
            raise ValueError(f"piece {piece.name}: group {piece.group!r} is not one of "
                             f"{', '.join(sorted(known))}")
    parts = [INTRO]
    for group, title in GROUPS:
        members = sorted((p for p in pieces.values() if p.group == group),
                         key=lambda p: p.name)
        if members:
            parts.append(f"## {title}\n")
            parts += [entry(piece) for piece in members]
    return "\n".join(parts).rstrip("\n") + "\n"


def main(argv):
    if len(argv) != 1:
        print("usage: python3 -m repo_infra.catalogue <catalogue.md to write>",
              file=sys.stderr)
        return 2
    target = pathlib.Path(argv[0])
    target.write_text(render(load_pieces()), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
